// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyudhcpeqdubzyvgjcls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dWRoY3BlcWR1Ynp5dmdqY2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTg0MTEsImV4cCI6MjA1NDc5NDQxMX0.Htgiab2562xZyf4_DNhzaVSIiZNaYCRUpWSeENZ7TFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);